// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "becomeascout": {
      "title": "Bli scout",
      "subtitle": "AV VÅR ÄVENTYRSGRUPP AV VÄNNER",
      "description": "I Scouterna hittar du både utmaningar och nya kompisar, oavsett var du bor eller hur du gammal du är. Här kan du uppleva äventyr i naturen, upptäcka nya sätt att lösa problem eller bara ha kul tillsammans medan vi utforskar världen. Och du är självklart med och bestämmer vad vi ska hitta på.",
      "button": "Bli scout",
      "readMore": "Läs mer"
    },
    "becomealeader": {
      "title": "Bli en ledare",
      "subtitle": "I SCOUTINGTRUPP MED KRAFT",
      "description": "Som vuxen finns det utmärkta möjligheter att utvecklas som ledare hos oss. Du behöver inte vara en erfaren seglare för att delta i våra aktiviteter. Du behöver inte heller vara en gammal scout för att bli ledare. Det enda kravet är att du har ett genuint intresse för att arbeta med unga människor och att du är intresserad av att arbeta ideellt i en välfungerande scoutkår. Kåren bekostar den utbildning du behöver för att fungera bra som scoutledare.",
      "button": "Bli en ledare",
      "readMore": "Läs mer"
    },
    "rentacabin": {
      "title": "Hyr en mysig stuga",
      "subtitle": "ATT UTFORSKA NATURENS FRIHET",
      "description": "I Scouterna hittar du både utmaningar och nya kompisar, oavsett var du bor eller hur du gammal du är. Här kan du uppleva äventyr i naturen, upptäcka nya sätt att lösa problem eller bara ha kul tillsammans medan vi utforskar världen. Och du är självklart med och bestämmer vad vi ska hitta på.",
      "button": "Hyr en stuga",
      "readMore": "Läs mer"
    },
    "becomeapartner": {
      "title": "Bli en partner",
      "subtitle": "ATT UTFORSKA TEMA VÅR STOLTHET ÖVER NÄSTA LEDARE NATURFRIHET",
      "description": "Som vuxen finns det utmärkta möjligheter att utvecklas som ledare hos oss. Du behöver inte vara en erfaren seglare för att delta i våra aktiviteter. Du behöver inte heller vara en gammal scout för att bli ledare. Det enda kravet är att du har ett genuint intresse för att arbeta med unga människor och att du är intresserad av att arbeta ideellt i en välfungerande scoutkår. Kåren bekostar den utbildning du behöver för att fungera bra som scoutledare.",
      "button": "Bli en partner",
      "readMore": "Läs mer"
    }
  },
  "cards": {
    "button": "Visa inlägget",
    "title": "Tidigare händelser inom HSS"
  },
  "aboutus": {
    "title": "Om oss",
    "descriptionOne": "Hässelby Strands Sjöscoutkår (HSS) är en traditionsrik ideell ungdomsverksamhet med fokus på scouting och båtliv. Vi är religiöst och politisk obundna, och medlem i Svenska Scoutförbundet, som med ca 65.000 medlemmar är en av Sveriges största ungdomsorganisationer.",
    "descriptionTwo": "Målet med vår verksamhet är att ge barn och ungdomar möjligheten att uppleva naturen, båtlivet, sjömanskapet, utmaningarna och - framförallt - kamratskapet. Grundidén är Learning by doing. Inom scouterna finns ingen avbytarbänk!",
    "descriptionThree": "Scoutkåren bildades 1959 och bedriver verksamheten i en trevlig lokal (kallad Ruffen) vid Mälarens strand i Hässelby. Kåren har omkring 130 glada medlemmar, äger fem segelbåtar, tio optimistjollar, två 2-kronor, snabb följebåt och en stor scoutstuga."
  },
  "departments": {
    "sjohumlor": {
      "title": "Sjöhumlor - ",
      "subtitle": "Spårare 8-9 år",
      "description": "Vid 8 års ålder kan man börja i HSS, dvs när man börjar i årskurs 2. Man blir då Spårarscout och medlem i avdelningen Sjöhumlorna. (Tidigare hette spårarscout ”miniorscout”) Vi har möten varje vecka samt övernattningar, både hajker och längre läger"
    },
    "kaparna": {
      "title": "Kaparna - ",
      "subtitle": "Upptäckare 10-11 år",
      "description": "På Kaparna börjar man vid 10 års ålder och stannar kvar i två år tills det är dags för nästa steg. (Tidigare hette upptäckarscout ”juniorscout”) På Kaparna stegras svårighetsgraden på uppgifterna."
    },
    "konvojen": {
      "title": "Konvojen - ",
      "subtitle": "Äventyrare 12-14 år",
      "description": "Vid 12 års ålder öppnas dörrarna till Äventyrarscouterna. I tre spännande år får man lära sig nyttiga saker inom sjömansskap och natur. (Tidigare hette äventyrarscout ”patrullscout”)"
    },
    "utmanare": {
      "title": "Utmanare - ",
      "subtitle": "15+ år",
      "description": "HSS utmanarscoutlag upphör aldrig att existera! Efter tiden som utmanarscout är man ett tätt sammansvetsat gäng. Det är inte ovanligt att man håller kontakten livet ut. (Tidigare hette denna avdelning ”seniorscout”)"
    },
    "familjescouting": {
      "title": "Familjescouting",
      "subtitle": "",
      "description": "Genom Familjescouting får barn under åtta år tillsammans med en eller flera vuxna på ett roligt och lekfullt sätt möta scouting. Familjescouting är dessutom ett utmärkt sätt att få in fler vuxna i kåren."
    }
  },
  "activities": {},
  "safetyguidelines": {
    "title": "Säkerhet och allmänna riktlinjer för scouter",
    "descriptionOne": "Självklart får det aldrig bli farligt - men vi kan inte ta bort alla riskmoment. Istället behöver vi använda vår fantasi för att tänka till innan vi genomför olika aktiviteter.",
    "descriptionTwo": "Inga säkerhetsregler i världen hjälper när olyckan redan har hänt. Därför är det viktigt att du som är ledare och ansvarig för verksamhet i Scouterna har förberett dig och din grupp väl innan ni ger er iväg på äventyr.",
    "policyOne": {
      "title": "HSS flytvästpolicy",
      "description": "Koppling till HSS Krisplan och Scouternas riktlinjer i “Säker Scout”. För att kunna ge alla scouter, och deras vårdnadshavare, tydliga direktiv i vilken typ av flytväst HSS rekommenderar, har HSS styrelse tagit fram denna policy.",
      "link": "Ladda ner den här (pdf)"
    },
    "policyTwo": {
      "title": "HSS märkessystem",
      "description": "För att alla scouter i HSS ska få möjlighet att ta märken på rätt termin har styrelsen beslutat om följande märkessystem den 14 januari 2025. Avdelningarna får självklart bestämma annorlunda, men tänk på att det kan bli krångligt för nästa gäng ...",
      "link": "Ladda ner den här (pdf)"
    },
    "policyThree": {
      "title": "HSS Trygga möten policy",
      "description": "Scouterna centralt initierade arbetet med Trygga Möten 2005 för att stärka ledare i att agera när barn och unga far illa. Målet är att ha en bred kunskap om potentiella risker för att förebygga diskriminering och övergrepp.",
      "link": "Ladda ner den här (pdf)"
    },
    "policyFour": {
      "title": "Vår fotopolicy",
      "description": "Vi fotograferar våra aktiviteter och använder bilderna på vår hemsida och i sociala medier för att göra reklam för vår verksamhet. Vi publicerar aldrig namn på våra scouter. Genom att vara medlem i HSS samtycker man till detta.",
      "link": "Ladda ner den här (pdf)"
    }
  },
  "contactus": {
    "title": "Kontakta oss",
    "subtitle": "Så här gör du för att komma i kontakt med oss",
    "fieldOne": "Fullständigt namn",
    "fieldTwo": "Meddelande till oss",
    "fieldThree": "E-postadress",
    "button": "Skicka"
  },
  "becomeascout": {},
  "becomealeader": {},
  "reserveacamp": {},
  "becomeapartner": {},
  "navbar": {
    "becomeascout": "Bli scout",
    "becomealeader": "Bli ledare",
    "reserveacamp": "Boka ett läger",
    "contactus": "Kontakta oss",
    "aboutus": "Om oss",
    "menulabel": "Mer",
    "moreMenu": {
      "activities": "Aktiviteter",
      "history": "Historia",
      "safety": "Säkerhet"
    }
  },
  "googlemap": {
    "emailLabel": "Epost",
    "findUsLabel": "Hitta till oss",
    "locations": {
      "myset": {
        "title": "Hajkstugan Myset",
        "description": "Vår mysiga stuga i skogen som används för övernattningar, hajk och landbaserade aktiviteter."
      },
      "ruffen": {
        "title": "Studentkårsrummet",
        "description": "Detta är vår huvudsakliga plats vid vattnet, där vi håller våra veckomöten."
      },
      "shipyard": {
        "title": "Varvet",
        "description": "Detta är vårt båtvarv där vi utför underhåll, reparationer och vinterförvaring. "
      },
      "boat-club": {
        "title": "Båtklubben",
        "description": "Här har vi våra hamnplatser för kårens större båtar under sommarhalvåret."
      }
    }
  },
  "footer": {}
};
export default messages;