// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "title": "Äventyr och kompisar!",
    "subtitle": "Välkommen till Hässelby Strands Sjöscoutkår. Äventyr på riktigt!"
  },
  "home": {
    "becomeascout": {
      "title": "Bli scout",
      "subtitle": "AV VÅR ÄVENTYRSGRUPP AV VÄNNER",
      "description": "I Scouterna hittar du både utmaningar och nya kompisar, oavsett var du bor eller hur du gammal du är. Här kan du uppleva äventyr i naturen, upptäcka nya sätt att lösa problem eller bara ha kul tillsammans medan vi utforskar världen. Och du är självklart med och bestämmer vad vi ska hitta på.",
      "button": "Bli scout",
      "readMore": "Läs mer"
    },
    "becomealeader": {
      "title": "Bli en ledare",
      "subtitle": "I SCOUTINGTRUPP MED KRAFT",
      "description": "Som vuxen finns det utmärkta möjligheter att utvecklas som ledare hos oss. Du behöver inte vara en erfaren seglare för att delta i våra aktiviteter. Du behöver inte heller vara en gammal scout för att bli ledare. Det enda kravet är att du har ett genuint intresse för att arbeta med unga människor och att du är intresserad av att arbeta ideellt i en välfungerande scoutkår. Kåren bekostar den utbildning du behöver för att fungera bra som scoutledare.",
      "button": "Bli en ledare",
      "readMore": "Läs mer"
    },
    "rentacabin": {
      "title": "Hyr en mysig stuga",
      "subtitle": "ATT UTFORSKA NATURENS FRIHET",
      "description": "I Scouterna hittar du både utmaningar och nya kompisar, oavsett var du bor eller hur du gammal du är. Här kan du uppleva äventyr i naturen, upptäcka nya sätt att lösa problem eller bara ha kul tillsammans medan vi utforskar världen. Och du är självklart med och bestämmer vad vi ska hitta på.",
      "button": "Hyr en stuga",
      "readMore": "Läs mer"
    },
    "becomeapartner": {
      "title": "Bli en partner",
      "subtitle": "ATT UTFORSKA TEMA VÅR STOLTHET ÖVER NÄSTA LEDARE NATURFRIHET",
      "description": "Som vuxen finns det utmärkta möjligheter att utvecklas som ledare hos oss. Du behöver inte vara en erfaren seglare för att delta i våra aktiviteter. Du behöver inte heller vara en gammal scout för att bli ledare. Det enda kravet är att du har ett genuint intresse för att arbeta med unga människor och att du är intresserad av att arbeta ideellt i en välfungerande scoutkår. Kåren bekostar den utbildning du behöver för att fungera bra som scoutledare.",
      "button": "Bli en partner",
      "readMore": "Läs mer"
    }
  },
  "cards": {
    "button": "Visa inlägget",
    "title": "Se våra äventyr på Instagram"
  },
  "InstagramSlider": {
    "title": "Senaste inläggen på Instagram",
    "viewPost": "Visa inlägg"
  },
  "aboutus": {
    "title": "Om oss",
    "descriptionOne": "Hässelby Strands Sjöscoutkår (HSS) är en traditionsrik ideell ungdomsverksamhet med fokus på scouting och båtliv. Vi är religiöst och politisk obundna, och medlem i Svenska Scoutförbundet, som med ca 65.000 medlemmar är en av Sveriges största ungdomsorganisationer.",
    "descriptionTwo": "Målet med vår verksamhet är att ge barn och ungdomar möjligheten att uppleva naturen, båtlivet, sjömanskapet, utmaningarna och - framförallt - kamratskapet. Grundidén är Learning by doing. Inom scouterna finns ingen avbytarbänk!",
    "descriptionThree": "Scoutkåren bildades 1959 och bedriver verksamheten i en trevlig lokal (kallad Ruffen) vid Mälarens strand i Hässelby. Kåren har omkring 130 glada medlemmar, äger fem segelbåtar, tio optimistjollar, två 2-kronor, snabb följebåt och en stor scoutstuga.",
    "linkTitle": "Upptäck våra scoutavdelningar",
    "button": "Till avdelningarna"
  },
  "departments": {
    "sjohumlor": {
      "title": "Sjöhumlor - ",
      "subtitle": "Spårare 8-9 år",
      "description": "Vid 8 års ålder kan man börja i HSS, dvs när man börjar i årskurs 2. Man blir då Spårarscout och medlem i avdelningen Sjöhumlorna. (Tidigare hette spårarscout ”miniorscout”) Vi har möten varje vecka samt övernattningar, både hajker och längre läger",
      "fullDescription": "Vid 8 års ålder kan man börja i HSS, dvs när man börjar i årskurs 2. Man blir då Spårarscout och medlem i avdelningen Sjöhumlorna. (Tidigare hette spårarscout ”miniorscout”)\nVi har möten varje vecka samt övernattningar, både hajker och längre läger. Här får barnen lära sig knopar, grundläggande naturkunskap och sjömanskap på ett lekfullt sätt.\nDu lär dig något nytt nästan varje dag i Scouterna, det är alltid roliga saker men ibland är de också väldigt bra att kunna. Som att tälja med kniv eller lägga bandage på någon som gjort sig illa. Till skillnad från hur man gör i skolan läser vi inga böcker om knivar och bandage, vi lär oss genom att göra, genom att prova på allt på riktigt istället. Medan vi gör det samarbetar vi i patruller, små grupper där alla är med och bestämmer. Det är smart, för tillsammans kan man alltid hjälps åt att hitta på ännu roligare saker.\nVi seglar optimistjollar och 2-kronor.\nSjöhumlorna har möten på måndagar i vår fina lokal Ruffen vid Hässelby Strandbad.\nNär man är scout gör man alltid sitt bästa och det gör inget om det råkar bli fel, därför brukar vi tänka lite på hur allting gått till så att vi blir bättre till nästa gång."
    },
    "kaparna": {
      "title": "Kaparna - ",
      "subtitle": "Upptäckare 10-11 år",
      "description": "På Kaparna börjar man vid 10 års ålder och stannar kvar i två år tills det är dags för nästa steg. (Tidigare hette upptäckarscout ”juniorscout”) På Kaparna stegras svårighetsgraden på uppgifterna.",
      "fullDescription": "På Kaparna börjar man vid 10 års ålder och stannar kvar i två år tills det är dags för nästa steg. (Tidigare hette upptäckarscout ”juniorscout”) På Kaparna stegras svårighetsgraden på uppgifterna.\nScouterna får lära sig segla optimist samt prova på att segla 2-krona samt kölbåt.\nEn färdigutbildad upptäckarscout kan bland annat hantera kniv, elda och släcka mindre bränder, segla optimist själv samt grundläggande sjukvård och sjösäkerhet.\nAvdelningen Kaparna har möten på tisdagar i vår lokal Ruffen vid Hässelby Strandbad.\nNär man är scout gör man alltid sitt bästa men det gör inget om det råkar bli fel, därför brukar vi tänka lite på hur allting gått till så att vi blir bättre till nästa gång."
    },
    "konvojen": {
      "title": "Konvojen - ",
      "subtitle": "Äventyrare 12-14 år",
      "description": "Vid 12 års ålder öppnas dörrarna till Äventyrarscouterna. I tre spännande år får man lära sig nyttiga saker inom sjömansskap och natur. (Tidigare hette äventyrarscout ”patrullscout”)",
      "fullDescription": "Vid 12 års ålder öppnas dörrarna till Äventyrarscouterna. I tre spännande år får man lära sig nyttiga saker inom sjömansskap och natur. (Tidigare hette äventyrarscout ”patrullscout”).\nHär börjar seglingen på allvar och det bär ut i skärgården om sommaren. När vi inte seglar tränar vi navigation och gör även traditionella landscoutaktiviteter.\nPå vintern när det är som kallast har vi en rejäl vinterhajk då vi bor i tält. En annan höjdare är det traditionella isvaksbadet som ingen patrullscout slipper ifrån…\nKonvojen har möten på torsdagar."
    },
    "utmanare": {
      "title": "Utmanare - ",
      "subtitle": "15+ år",
      "description": "HSS utmanarscoutlag upphör aldrig att existera! Efter tiden som utmanarscout är man ett tätt sammansvetsat gäng. Det är inte ovanligt att man håller kontakten livet ut. (Tidigare hette denna avdelning ”seniorscout”)",
      "fullDescription": "HSS utmanarscoutlag upphör aldrig att existera! Efter tiden som utmanarscout är man ett tätt sammansvetsat gäng. Det är inte ovanligt att man håller kontakten livet ut. (Tidigare hette denna avdelning ”seniorscout”).\nNär man kommer upp från äventyrarscouterna bildar man ett lag tillsammans med kullkamraterna. Sedan arbetar man mot att lära sig nya saker och anta svårare utmaningar för att öka sammanhållningen.\nUnder de första åren har man ledare med sig och allt eftersom man utvecklas blir man själv ledare på de andra avdelningarna.\nUtmanarscouterna seglar själva i skärgården när de uppnått tillräcklig kunskapsnivå.\nVarje utmanarscoutlag hittar på sitt eget namn (av tradition slutar de på -arne och laget kallas ”fjantarne” till dess att de kommit på ett eget namn).\nMötena sker på tisdagar eller onsdagar."
    },
    "familjescouting": {
      "title": "Familjescouting",
      "subtitle": "",
      "description": "Genom Familjescouting får barn under åtta år tillsammans med en eller flera vuxna på ett roligt och lekfullt sätt möta scouting. Familjescouting är dessutom ett utmärkt sätt att få in fler vuxna i kåren.",
      "fullDescription": "Familjescouting är till för barn under åtta år och en vuxen som barnet känner sig trygg med. Tillsammans upptäcker ni scouting genom lek, äventyr och roliga aktiviteter.\nBarn och vuxna är med sida vid sida och hjälps åt i aktiviteterna. Den vuxna ansvarar för barnet, men är också en viktig del av gemenskapen och deltar lika mycket som barnen.\nDen vuxna kan vara en förälder, mor- eller farförälder, släkting eller någon annan nära person.\nFokus i Familjescouting är att barn och vuxna får uppleva saker tillsammans och stärka sin relation."
    }
  },
  "activities": {},

  "safetyguidelines": {
    "title": "Säkerhet och allmänna riktlinjer för scouter",
    "descriptionOne": "Självklart får det aldrig bli farligt - men vi kan inte ta bort alla riskmoment. Istället behöver vi använda vår fantasi för att tänka till innan vi genomför olika aktiviteter.",
    "descriptionTwo": "Inga säkerhetsregler i världen hjälper när olyckan redan har hänt. Därför är det viktigt att du som är ledare och ansvarig för verksamhet i Scouterna har förberett dig och din grupp väl innan ni ger er iväg på äventyr.",
    "policyOne": {
      "title": "HSS flytvästpolicy",
      "description": "Koppling till HSS Krisplan och Scouternas riktlinjer i “Säker Scout”. För att kunna ge alla scouter, och deras vårdnadshavare, tydliga direktiv i vilken typ av flytväst HSS rekommenderar, har HSS styrelse tagit fram denna policy.",
      "link": "Ladda ner den här (pdf)"
    },
    "policyTwo": {
      "title": "HSS märkessystem",
      "description": "För att alla scouter i HSS ska få möjlighet att ta märken på rätt termin har styrelsen beslutat om följande märkessystem den 14 januari 2025. Avdelningarna får självklart bestämma annorlunda, men tänk på att det kan bli krångligt för nästa gäng ...",
      "link": "Ladda ner den här (pdf)"
    },
    "policyThree": {
      "title": "HSS Trygga möten policy",
      "description": "Scouterna centralt initierade arbetet med Trygga Möten 2005 för att stärka ledare i att agera när barn och unga far illa. Målet är att ha en bred kunskap om potentiella risker för att förebygga diskriminering och övergrepp.",
      "link": "Ladda ner den här (pdf)"
    },
    "policyFour": {
      "title": "Vår fotopolicy",
      "description": "Vi fotograferar våra aktiviteter och använder bilderna på vår hemsida och i sociala medier för att göra reklam för vår verksamhet. Vi publicerar aldrig namn på våra scouter. Genom att vara medlem i HSS samtycker man till detta.",
      "link": "Ladda ner den här (pdf)"
    }
  },
  "contactus": {
    "title": "Kontakta oss",
    "subtitle": "Har du frågor? Hör gärna av dig!",
    "fieldOne": "Fullständigt namn",
    "fieldTwo": "E-postadress",
    "fieldThree": "Meddelande",
    "button": "Skicka",
    "linksTitle": "Viktiga länkar",
    "memberTitle": "Vill du bli en av oss?",
    "formButton": "Intresseanmälan"
  },
  "becomeascout": {},
  "becomealeader": {
    "description": "Är du sugen på scouting och segling? Tveka inte, då ska du anmäla ditt intresse till HSS. Oavsett om du är 8 eller 100 år är du välkommen. För att anmäla dig till kölistan fyller du in en intresseanmälan nedan. Vi kontaktar dig när det blir en plats ledig.\n\nSom vuxen finns det utmärkta möjligheter att utvecklas som ledare hos oss. Ledarsituationen i kåren varierar, nu är vi i akut behov av ledare till Kaparna. Du behöver inte vara en erfaren seglare för att delta i vår verksamhet. Du behöver inte heller vara gammal scout för att bli ledare. Enda kravet är att du har ett genuint intresse av att jobba med ungdomar och att du är sugen på att arbeta ideellt i en välfungerande scoutkår. Kåren betalar för den utbildning du behöver för att fungera bra som scoutledare. Vi behöver alltid föräldrar som kan hjälpa till med stort som smått. Utan föräldrar ingen kår, så enkelt är det!\n\n”Scouterna har varit min bästa ledarskola. Där kan man bara leda med idéns kraft och förmågan att övertyga.”\n[Carl-Henrik Svanberg, fd VD för Ericsson, i Expressen 2003-02-07]\n\n”Inom scoutrörelsen finns ingen avbytarbänk.”\n[Anonym ledare i HSS]\n\n Välkommen!",
    "sectionHero": {
      "title": "Vill du bli en av oss?",
      "intro": "Här kanske ditt livs äventyr startar. I HSS finns det spännande utmaningar för stor som liten."
    },
    "button": {
      "content": "Bli ledare"
    }
  },
  "reserveacamp": {},
  "becomeapartner": {},
  "history": {
    "intro": {
      "date": "1950s",
      "title": "BÖRJAN",
      "description": "Scoutkåren bildades 1959 och bedriver verksamheten i en trevlig lokal (kallad Ruffen) vid Mälarens strand i Hässelby. Kåren har omkring 130 glada medlemmar, äger fem segelbåtar, tio optimistjollar, två 2-kronor, snabb följebåt och en stor scoutstuga.",
      "descriptionTwo": ""
    },
    "boatHistory": {
      "date": "",
      "title": "VÅR BÅTHISTORIA",
      "description": "Scoutkåren bildades 1959 och bedriver verksamheten i en trevlig lokal (kallad Ruffen) vid Mälarens strand i Hässelby. Kåren har omkring 130 glada medlemmar, äger fem segelbåtar, tio optimistjollar, två 2-kronor, snabb följebåt och en stor scoutstuga.",
      "descriptionTwo": ""
    },
    "buildingMyset": {
      "date": "1970's",
      "title": "BYGGA MYSET",
      "description": "Myset är vår stuga i Lövsta. Söndagen den 28 Januari 1968 invigdes Myset. Under tre år hade då HSS's Föräldraförening arbetat på stugan. Bygget kostade nära 50.000 kr, dessa pengar hade samlats in på basarer och lotterier. På invigningsdagen närvarade nära 400 förväntansfulla scouter och föräldrar. De fick bevittna när FF's ordförande Agne Stavegren formellt lämnade över nyckeln till HSS's ordförande Lennart Carlbom.",
      "descriptionTwo": "Här har vi lyckats hitta några bilder från en svunnen tid."
    },
    "expanding": {
      "date": "1990's",
      "title": "UTVIDGADE PROGRAM",
      "description": "Betydande utökning av verksamheten med nya åldersgrupper och specialiserade aktiviteter. Vi började erbjuda fler vattenbaserade aktiviteter och förblev trogna vårt sjöscoutarv.",
      "descriptionTwo": ""
    },
    "today": {
      "date": "Today",
      "title": "UTVIDGADE PROGRAM",
      "description": "Söndagen den 28 Januari 1968 invigdes Myset. Under tre år hade då HSS's Föräldraförening arbetat på stugan. Bygget kostade nära 50.000 kr, dessa pengar hade samlats in på basarer och lotterier. På invigningsdagen närvarade nära 400 förväntansfulla scouter och föräldrar. De fick bevittna när FF's ordförande Agne Stavegren formellt lämnade över nyckeln till HSS's ordförande Lennart Carlbom.",
      "descriptionTwo": ""
    }
  },
  "navbar": {
    "becomeascout": "Bli scout",
    "becomealeader": "Bli ledare",
    "ourcabin": "Vår stuga",
    "ourboats": "Våra båtar",
    "aboutus": "Om oss",
    "menulabel": "Mer",
    "moreMenu": {
      "history": "Historia",
      "safety": "Säkerhet",
      "contactus": "Kontakt"
    }
  },
  "googlemap": {
    "emailLabel": "Epost",
    "findUsLabel": "Hitta till oss",
    "locations": {
      "myset": {
        "title": "Hajkstugan Myset",
        "description": "Vår mysiga stuga i skogen som används för övernattningar, hajk och landbaserade aktiviteter."
      },
      "ruffen": {
        "title": "Studentkårsrummet",
        "description": "Detta är vår huvudsakliga plats vid vattnet, där vi håller våra veckomöten."
      },
      "shipyard": {
        "title": "Varvet",
        "description": "Detta är vårt båtvarv där vi utför underhåll, reparationer och vinterförvaring. "
      },
      "boat-club": {
        "title": "Båtklubben",
        "description": "Här har vi våra hamnplatser för kårens större båtar under sommarhalvåret."
      }
    }
  },
  "footer": {
    "logo": {
      "title": "Tillsammans kan vi göra mer!",
      "description": "Scouterna ger barn och unga från alla delar av samhället chansen att uppleva äventyr tillsammans och växa som individer."
    }
  },
  "DepartmentHero": {
    "intro": "För att gå med i vår scoutkår kan du göra en intresseanmälan som skickas direkt till vårt medlemsregister. Fyll i uppgifterna nedan så hör vi av oss till dig inom kort."
  },
  "back": "Tillbaka",
  "404": {
    "title": "Vi har drivit ur kurs!",
    "subtitle": "Den här sidan finns inte på våra sjökort. Den kan ha flyttats, eller aldrig blivit utmärkt från början.\nLåt oss sätta en ny kurs.",
    "button": "Tillbaka till hamnen"
  },
  "comingsoon": {
    "title": "Snart lättar vi ankare!",
    "subtitle": "Sidan är under uppbyggnad och vi förbereder nästa del av resan.\nTitta gärna tillbaka lite senare.",
    "button": "Till startsidan"
  }
};
export default messages;